/******************************************************************************
 * Qwt Widget Library
 * Copyright (C) 1997   Josef Wilgen
 * Copyright (C) 2002   Uwe Rathmann
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the Qwt License, Version 1.0
 *
 * Modified by ChenZongYan in 2024 <czy.t@163.com>
 *   Summary of major modifications (see ChangeLog.md for full history):
 *   1. CMake build system & C++11 throughout.
 *   2. Core panner/ zoomer refactored:
 *        - QwtPanner -> QwtCachePanner (pixmap-cache version)
 *        - New real-time QwtPlotPanner derived from QwtPicker.
 *   3. Zoomer supports multi-axis.
 *   4. Parasite-plot framework:
 *        - QwtFigure, QwtPlotParasiteLayout, QwtPlotTransparentCanvas,
 *        - QwtPlotScaleEventDispatcher, built-in pan/zoom on axis.
 *   5. New picker: QwtPlotSeriesDataPicker (works with date axis).
 *   6. Raster & color-map extensions:
 *        - QwtGridRasterData (2-D table + interpolation)
 *        - QwtLinearColorMap::stopColors(), stopPos() API rename.
 *   7. Bar-chart: expose pen/brush control.
 *   8. Amalgamated build: single QwtPlot.h / QwtPlot.cpp pair in src-amalgamate.
 *****************************************************************************/

#include "qwt_picker_machine.h"
#include "qwt_event_pattern.h"

#include <qevent.h>

/**
 * @brief Constructor
 * @param[in] type Selection type for this state machine
 */
QwtPickerMachine::QwtPickerMachine(SelectionType type) : m_selectionType(type), m_state(0)
{
}

/**
 * @brief Destructor
 */
QwtPickerMachine::~QwtPickerMachine()
{
}

/**
 * @brief Return the selection type
 * @return Selection type of this state machine
 */
QwtPickerMachine::SelectionType QwtPickerMachine::selectionType() const
{
    return m_selectionType;
}

/**
 * @brief Return the current state
 * @return Current state value
 */
int QwtPickerMachine::state() const
{
    return m_state;
}

/**
 * @brief Change the current state
 * @param[in] state New state value
 */
void QwtPickerMachine::setState(int state)
{
    m_state = state;
}

/**
 * @brief Set the current state to 0 (initial state)
 */
void QwtPickerMachine::reset()
{
    setState(0);
}

/**
 * @brief Constructor
 */
QwtPickerTrackerMachine::QwtPickerTrackerMachine() : QwtPickerMachine(NoSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] e Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerTrackerMachine::transition(const QwtEventPattern&, const QEvent* e)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (e->type()) {
    case QEvent::Enter:
    case QEvent::MouseMove: {
        if (state() == 0) {
            cmdList += Begin;
            cmdList += Append;
            setState(1);
        } else {
            cmdList += Move;
        }
        break;
    }
    case QEvent::Leave: {
        cmdList += Remove;
        cmdList += End;
        setState(0);
    }
    default:
        break;
    }

    return cmdList;
}

/**
 * @brief Constructor
 */
QwtPickerClickPointMachine::QwtPickerClickPointMachine() : QwtPickerMachine(PointSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] event Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerClickPointMachine::transition(const QwtEventPattern& eventPattern,
                                                                          const QEvent* event)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (event->type()) {
    case QEvent::MouseButtonPress: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            cmdList += Begin;
            cmdList += Append;
            cmdList += End;
        }
        break;
    }
    case QEvent::KeyPress: {
        const QKeyEvent* keyEvent = static_cast< const QKeyEvent* >(event);
        if (eventPattern.keyMatch(QwtEventPattern::KeySelect1, keyEvent)) {
            if (!keyEvent->isAutoRepeat()) {
                cmdList += Begin;
                cmdList += Append;
                cmdList += End;
            }
        }
        break;
    }
    default:
        break;
    }

    return cmdList;
}

/**
 * @brief Constructor
 */
QwtPickerDragPointMachine::QwtPickerDragPointMachine() : QwtPickerMachine(PointSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] event Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerDragPointMachine::transition(const QwtEventPattern& eventPattern,
                                                                         const QEvent* event)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (event->type()) {
    case QEvent::MouseButtonPress: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            if (state() == 0) {
                cmdList += Begin;
                cmdList += Append;
                setState(1);
            }
        }
        break;
    }
    case QEvent::MouseMove:
    case QEvent::Wheel: {
        if (state() != 0)
            cmdList += Move;
        break;
    }
    case QEvent::MouseButtonRelease: {
        if (state() != 0) {
            cmdList += End;
            setState(0);
        }
        break;
    }
    case QEvent::KeyPress: {
        const QKeyEvent* keyEvent = static_cast< const QKeyEvent* >(event);
        if (eventPattern.keyMatch(QwtEventPattern::KeySelect1, keyEvent)) {
            if (!keyEvent->isAutoRepeat()) {
                if (state() == 0) {
                    cmdList += Begin;
                    cmdList += Append;
                    setState(1);
                } else {
                    cmdList += End;
                    setState(0);
                }
            }
        }
        break;
    }
    default:
        break;
    }

    return cmdList;
}

/**
 * @brief Constructor
 */
QwtPickerClickRectMachine::QwtPickerClickRectMachine() : QwtPickerMachine(RectSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] event Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerClickRectMachine::transition(const QwtEventPattern& eventPattern,
                                                                         const QEvent* event)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (event->type()) {
    case QEvent::MouseButtonPress: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            switch (state()) {
            case 0: {
                cmdList += Begin;
                cmdList += Append;
                setState(1);
                break;
            }
            case 1: {
                // Uh, strange we missed the MouseButtonRelease
                break;
            }
            default: {
                cmdList += End;
                setState(0);
            }
            }
        }
        break;
    }
    case QEvent::MouseMove:
    case QEvent::Wheel: {
        if (state() != 0)
            cmdList += Move;
        break;
    }
    case QEvent::MouseButtonRelease: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            if (state() == 1) {
                cmdList += Append;
                setState(2);
            }
        }
        break;
    }
    case QEvent::KeyPress: {
        const QKeyEvent* keyEvent = static_cast< const QKeyEvent* >(event);
        if (eventPattern.keyMatch(QwtEventPattern::KeySelect1, keyEvent)) {
            if (!keyEvent->isAutoRepeat()) {
                if (state() == 0) {
                    cmdList += Begin;
                    cmdList += Append;
                    setState(1);
                } else {
                    if (state() == 1) {
                        cmdList += Append;
                        setState(2);
                    } else if (state() == 2) {
                        cmdList += End;
                        setState(0);
                    }
                }
            }
        }
        break;
    }
    default:
        break;
    }

    return cmdList;
}

/**
 * @brief Constructor
 */
QwtPickerDragRectMachine::QwtPickerDragRectMachine() : QwtPickerMachine(RectSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] event Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerDragRectMachine::transition(const QwtEventPattern& eventPattern,
                                                                        const QEvent* event)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (event->type()) {
    case QEvent::MouseButtonPress: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            if (state() == 0) {
                cmdList += Begin;
                cmdList += Append;
                cmdList += Append;
                setState(2);
            }
        }
        break;
    }
    case QEvent::MouseMove:
    case QEvent::Wheel: {
        if (state() != 0)
            cmdList += Move;
        break;
    }
    case QEvent::MouseButtonRelease: {
        if (state() == 2) {
            cmdList += End;
            setState(0);
        }
        break;
    }
    case QEvent::KeyPress: {
        if (eventPattern.keyMatch(QwtEventPattern::KeySelect1, static_cast< const QKeyEvent* >(event))) {
            if (state() == 0) {
                cmdList += Begin;
                cmdList += Append;
                cmdList += Append;
                setState(2);
            } else {
                cmdList += End;
                setState(0);
            }
        }
        break;
    }
    default:
        break;
    }

    return cmdList;
}

/**
 * @brief Constructor
 */
QwtPickerPolygonMachine::QwtPickerPolygonMachine() : QwtPickerMachine(PolygonSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] event Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerPolygonMachine::transition(const QwtEventPattern& eventPattern,
                                                                       const QEvent* event)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (event->type()) {
    case QEvent::MouseButtonPress: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            if (state() == 0) {
                cmdList += Begin;
                cmdList += Append;
                cmdList += Append;
                setState(1);
            } else {
                cmdList += Append;
            }
        }
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect2, static_cast< const QMouseEvent* >(event))) {
            if (state() == 1) {
                cmdList += End;
                setState(0);
            }
        }
        break;
    }
    case QEvent::MouseMove:
    case QEvent::Wheel: {
        if (state() != 0)
            cmdList += Move;
        break;
    }
    case QEvent::KeyPress: {
        const QKeyEvent* keyEvent = static_cast< const QKeyEvent* >(event);
        if (eventPattern.keyMatch(QwtEventPattern::KeySelect1, keyEvent)) {
            if (!keyEvent->isAutoRepeat()) {
                if (state() == 0) {
                    cmdList += Begin;
                    cmdList += Append;
                    cmdList += Append;
                    setState(1);
                } else {
                    cmdList += Append;
                }
            }
        } else if (eventPattern.keyMatch(QwtEventPattern::KeySelect2, keyEvent)) {
            if (!keyEvent->isAutoRepeat()) {
                if (state() == 1) {
                    cmdList += End;
                    setState(0);
                }
            }
        }
        break;
    }
    default:
        break;
    }

    return cmdList;
}

/**
 * @brief Constructor
 */
QwtPickerDragLineMachine::QwtPickerDragLineMachine() : QwtPickerMachine(PolygonSelection)
{
}

/**
 * @brief Transition function that processes events and returns commands
 * @param[in] eventPattern Event pattern for matching
 * @param[in] event Event to process
 * @return List of commands generated by the transition
 */
QList< QwtPickerMachine::Command > QwtPickerDragLineMachine::transition(const QwtEventPattern& eventPattern,
                                                                        const QEvent* event)
{
    QList< QwtPickerMachine::Command > cmdList;

    switch (event->type()) {
    case QEvent::MouseButtonPress: {
        if (eventPattern.mouseMatch(QwtEventPattern::MouseSelect1, static_cast< const QMouseEvent* >(event))) {
            if (state() == 0) {
                cmdList += Begin;
                cmdList += Append;
                cmdList += Append;
                setState(1);
            }
        }
        break;
    }
    case QEvent::KeyPress: {
        if (eventPattern.keyMatch(QwtEventPattern::KeySelect1, static_cast< const QKeyEvent* >(event))) {
            if (state() == 0) {
                cmdList += Begin;
                cmdList += Append;
                cmdList += Append;
                setState(1);
            } else {
                cmdList += End;
                setState(0);
            }
        }
        break;
    }
    case QEvent::MouseMove:
    case QEvent::Wheel: {
        if (state() != 0)
            cmdList += Move;

        break;
    }
    case QEvent::MouseButtonRelease: {
        if (state() != 0) {
            cmdList += End;
            setState(0);
        }
    }
    default:
        break;
    }

    return cmdList;
}
