#ifndef QWT_VERSION_INFO_H
#define QWT_VERSION_INFO_H

/**
 * @file This file is automatically generated by CMake from qwt_version_info.h.in.
 * Any changes made to this file will be overwritten.
 */

/**
 * @def Qwt numeric version {MAJ}.MIN.PAT
 */
#ifndef QWT_VERSION_MAJ
#define QWT_VERSION_MAJ 7
#endif

/**
 * @def Qwt numeric version MAJ.{MIN}.PAT
 */
#ifndef QWT_VERSION_MIN
#define QWT_VERSION_MIN 3
#endif

/**
 * @def Qwt numeric version MAJ.MIN.{PAT}
 */
#ifndef QWT_VERSION_PAT
#define QWT_VERSION_PAT 1
#endif

/**
 * @def Version string
 */
#ifndef QWT_VERSION_STR
#define QWT_VERSION_STR "7.3.1"
#endif

#endif // QWT_VERSION_INFO_H
